### ISSUE TITLE
ERROR! Unexpected Exception: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3'))

### ISSUE THREAD

**Issue by PeterMika** [geerlingguy/packer-centos-7#12]
When reaching step of provisioning Virtualbox centos7 image I get a failure. My guess is newer Ansible version requires a newer version of setuptools then is currently not included on centos7 image causing provisioning to fail. see below
`
==> virtualbox-iso: Provisioning with Ansible...
    virtualbox-iso: Creating Ansible staging directory...
    virtualbox-iso: Creating directory: /tmp/packer-provisioner-ansible-local
    virtualbox-iso: Uploading main Playbook file...
    virtualbox-iso: Uploading inventory file...
    virtualbox-iso: Uploading role directories...
    virtualbox-iso: Creating directory: /tmp/packer-provisioner-ansible-local/roles/geerlingguy.packer-rhel
    virtualbox-iso: Creating directory: /tmp/packer-provisioner-ansible-local/roles/geerlingguy.nfs
virtualbox-iso: Executing Ansible: cd /tmp/packer-provisioner-ansible-local && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/main.yml -c local -i /tmp/packer-provisioner-ansible-local/packer-provisioner-ansible-local185464981
    virtualbox-iso: ERROR! Unexpected Exception: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3'))
    virtualbox-iso: the full traceback was:
    virtualbox-iso:
    virtualbox-iso: Traceback (most recent call last):
    virtualbox-iso: File "/usr/bin/ansible-playbook", line 73, in <module>
    virtualbox-iso: mycli = getattr(**import**("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 30, in <module>
    virtualbox-iso: from ansible.executor.playbook_executor import PlaybookExecutor
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 27, in <module>
    virtualbox-iso: from ansible.executor.task_queue_manager import TaskQueueManager
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    virtualbox-iso: from ansible.executor.play_iterator import PlayIterator
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/executor/play_iterator.py", line 29, in <module>
    virtualbox-iso: from ansible.playbook.block import Block
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/playbook/**init**.py", line 25, in <module>
    virtualbox-iso: from ansible.playbook.play import Play
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 27, in <module>
    virtualbox-iso: from ansible.playbook.base import Base
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 35, in <module>
    virtualbox-iso: from ansible.parsing.dataloader import DataLoader
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 32, in <module>
    virtualbox-iso: from ansible.parsing.vault import VaultLib
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/ansible/parsing/vault/**init**.py", line 67, in <module>
    virtualbox-iso: from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
    virtualbox-iso: File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    virtualbox-iso: from cryptography.hazmat.backends.interfaces import HashBackend
    virtualbox-iso: File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/**init**.py", line 7, in <module>
    virtualbox-iso: import pkg_resources
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    virtualbox-iso: parse_requirements(**requires**), Environment()
    virtualbox-iso: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    virtualbox-iso: raise VersionConflict(dist,req) # XXX put more info here
    virtualbox-iso: VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3'))'

**Comment by geerlingguy** [comment]
I was running into this issue when running from El Capitan on CentOS 7... see: http://stackoverflow.com/a/33687813/100134

> `pip install --upgrade setuptools --user python`
