### ISSUE TITLE
ssh hangs on centos7 version 1.1.4

### ISSUE THREAD

**Issue by cdmo** [geerlingguy/packer-centos-7#15]
Tried to start a new DrupalVM box up using geerlingguy/centos7 1.1.4 and kept getting hung at the point where ssh logins occur. No error messages would show either, it would just sort of hang for a while and then exit out saying it couldn't get ssh access. I am assuming this is a problem with the 1.1.4 release because when I made a Vagrantfile.local and added the following line, destroyed and ran up again, it was able to execute ssh.

config.vm.box_version = "1.1.3"

See geerlingguy/drupal-vm#960

**Comment by geerlingguy** [comment]
I'm 99% sure this is due to running VirtualBox 5.0.x instead of 5.1.6 or later. See related:
- https://github.com/chef/bento/issues/688

The fix if you need to remain on an older VirtualBox release is to install the box version 1.1.3 instead.

**Comment by geerlingguy** [comment]
Going to close this issue and the other on Drupal VM, since there's a workaround (don't upgrade box until you've upgraded VirtualBox itself), and since the main issue causing upgrade to be difficult in your case seems to be https://github.com/geerlingguy/drupal-vm/issues/912
