### ISSUE TITLE
Add cifs-utils package

### ISSUE THREAD

**Issue by billfergus** [geerlingguy/packer-centos-7#20]
cifs-utils is needed for the machine to mount smb shares.

See: https://github.com/geerlingguy/drupal-vm/issues/1147#issuecomment-279084172

**Comment by geerlingguy** [comment]
Working on a new box now... will also update my CentOS 6 box.

**Comment by geerlingguy** [comment]
Box is uploading. I'm going to close this out as I'll add the box to Atlas in the next hour or so after the upload is complete.

**Comment by billfergus** [comment]
I think [a hiccup](https://aws.amazon.com/message/41926/) might have affected Atlas at that time.

**Comment by geerlingguy** [comment]
@billfergus - Just a hiccup... ha!

Now it's there: https://atlas.hashicorp.com/geerlingguy/boxes/centos7/versions/1.1.8

**Comment by billfergus** [comment]
@geerlingguy I am not sure if this made it into the box because it is not installed with a fresh build using 1.1.8.
