### ISSUE TITLE
Feature Request: Make this libVirt compatible

### ISSUE THREAD

**Issue by james-nesbitt** [geerlingguy/packer-centos-7#24]
I am not sure what is required or how feasible it is to create vagrant images that work across providers

It would be nice if this image could work with the vagrant libvirt plugin, using QEMU/KVM as a backend, instead of virtualbox/vmware.  I know that vbox is the goto standard, but the kvm implementation is much better on a linux host, as the filesharing can be done much better (with plan-9 fs overlay drivers)

Users using linux hosts have much better options for virtual machines than vbox, with much better core handling of VMs.  Being forced to use box has great impact, as only one VM kernel driver can take control of the CPU vm architecture at a time.

https://github.com/vagrant-libvirt/vagrant-libvirt

**Comment by geerlingguy** [comment]
I would like to do this at some point (for all the packer builds I maintain), I just haven't had time yet.

**Comment by james-nesbitt** [comment]
sorry for blanking on this for so long.

The big KVM weaknesses would likely be:

1. volume overlay is typicall low performance
2. common KVM networks are userland, and also quick low performance.

**Comment by geerlingguy** [comment]
Closing as all development work for my packer boxes is moving into a central repository, see: geerlingguy/packer-boxes#45
