### ISSUE TITLE
Can't mount native share shared directory

### ISSUE THREAD

**Issue by cdmo** [geerlingguy/packer-centos-7#25]
Just tried 1.2.1 in conjunction with DrupalVM and the provisioning bailed out early right when it attempts to mount shared folders. I rolled back to 1.2.0 and it worked fine.

DrupalVM 4.4.2
VirtualBox 5.1.20
Ansible 2.3
Vagrant 1.8.6 (edit)

Just wanted to report. Thanks!

**Comment by geerlingguy** [comment]
@cdmo - Hmm... Just wondering - do you have the `vagrant-vbguest` plugin installed? Also, could you possibly try with Vagrant 1.9.4 as well?

I know CentOS 7 has had the most annoying issues with Vagrant lately :/

**Comment by cdmo** [comment]
I'll give it a shot and report back.

This is the error message output btw:

```
==> ulvm: Mounting shared folders...
    ulvm: /vagrant => /Users/cdm32/projects/drupalvm
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: wrong fs type, bad option, bad superblock on vagrant,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

**Comment by karlkedrovsky** [comment]
Not sure if this will be helpful but I'm getting this same error by running:

    vagrant init geerlingguy/ubuntu1604
    vagrant up

I'm using VirtualBox 1.5.22 and Vagrant 1.9.4 and 1.8.7.

**Comment by karlkedrovsky** [comment]
Figures, as soon as I post that last comment I figured out what the problem was - I didn't have the vagrant-vbguest plugin installed. Running the following fixed it for me.

    vagrant plugin install vagrant-vbguest

**Comment by geerlingguy** [comment]
@karlkedrovsky - D'oh, VirtualBox releases are getting to be too frequent—I just updated the built in guest additions to 5.1.20 a week or so ago. But yes, usually the `vagrant-vbguest` plugin will fix that.

**Comment by wapacro** [comment]
@geerlingguy do you plan to release the [box version 1.2.2](https://atlas.hashicorp.com/geerlingguy/boxes/centos7/versions/1.2.2) anytime soon? Because installing the plugin didn't fix the problem for me. The plugin always  rolls back to guest additions version 5.1.20 instead of 5.1.22.

**Comment by mohsenSy** [comment]
Hi I had the same issue today virtualbox version `5.1.22`, vagrant version `1.9.1` and box version `1.2.1`

```
 Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: wrong fs type, bad option, bad superblock on vagrant,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so
```

**Comment by geerlingguy** [comment]
@wapacro - I've been having trouble in local testing with 1.2.2, which is why it hasn't been released yet. It seems something is messing up native shares with my build. I'll try building again.

Note that you might be able to work around it with `vagrant plugin install vagrant-vbguest`.

**Comment by cdmo** [comment]
just fyi, I installed `vagrant-vbguest` and it didn't work.

**Comment by cdmo** [comment]
Sorry for the reply string here, but I Tried with Vagrant `1.9.4` as well and got the same result.

**Comment by cdmo** [comment]
Success! I upgraded to the very latest VirtualBox (`5.1.22`) and the shared folders mounted. For the record:

`Vagrant 1.9.4`
`vagrant-vbguest 0.14.1`

So... close this I guess?

**Comment by geerlingguy** [comment]
@cdmo - Sounds good, glad you got it working! I'll close this, and just leave this final note for anyone else coming here in the future: trying to stick with a winning version combination for Vagrant + VirtualBox + CentOS boxes is very difficult... this isn't the first time being off by a version or two has caused grief!

**Comment by cdmo** [comment]
Thanks! Yah tell me about it, this isn't the time it's caused grief for me! Would be nice to have a way to lock the box version in the config.yml file on drupalVM. I'm guessing this wouldn't be too difficult actually? Regardless yes this is closed.
