### ISSUE TITLE
A source of Ansible packages for RHEL/CentOS will change soon

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/packer-centos-7#27]
> In order to align better with Red Hat processes, the Ansible team will be making some changes in how Ansible packages are distributed to the community. 
> 
> For users of RHEL/CentOS/Scientific Linux version 7, the Ansible package will transition from the EPEL repository to the Extras channel.  There will be no change for version 6 of RHEL/CentOS/Scientific Linux as Extras is not a part of version 6.   

[Source](https://groups.google.com/forum/?utm_medium=email&utm_source=footer&utm_source=DevOps%27ish+Weekly&utm_campaign=44f65197a6-devopsish-033&utm_medium=email&utm_term=0_eab566bc9f-44f65197a6-40899129#!msg/ansible-project/PVJlQdHCDHU/HovBfx1FBwAJ)

**Comment by geerlingguy** [comment]
:-/

**Comment by geerlingguy** [comment]
More info:

  - RPMs are here: http://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
  - CentOS 7 Extras: http://mirror.centos.org/centos/7/extras/x86_64/Packages/

And from CentOS 7's yum docs:

> CentOS Extras - In CentOS 5 and 6, packages that provide additional functionality to CentOS without breaking upstream compatibility or updating base components, but are not tested by upstream or available in the upstream product. In CentOS 7 this is an upstream repository, as well as additional CentOS packages. The CentOS development team have tested every item in this repository and they all work with CentOS. This repository is shipped with CentOS and is enabled by default.

So I can just remove the `epel-release` installation, and install `ansible` with yum, I think.

**Comment by geerlingguy** [comment]
(Also, current build worked like that, so I'm going to go ahead and close this — will commit the fix in a few minutes.)
