### ISSUE TITLE
Warning: Authentication failure. Retrying...

### ISSUE THREAD

**Issue by mikev1963** [geerlingguy/packer-centos-7#31]
After building this image I get these errors:

    virtualbox: Warning: Remote connection disconnect. Retrying...
    virtualbox: Warning: Connection reset. Retrying...
    virtualbox: Warning: Remote connection disconnect. Retrying...
    virtualbox: Warning: Connection reset. Retrying...
  
    .....

    virtualbox: Warning: Authentication failure. Retrying...
    virtualbox: Warning: Authentication failure. Retrying...
    virtualbox: Warning: Authentication failure. Retrying...
    virtualbox: Warning: Authentication failure. Retrying...

   ....

**Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.**

**Comment by mikev1963** [comment]
After doing some testing this line in the Vagrant file is causing the authentication Failures.
    _config.vm.synced_folder '.', '/vagrant', type: 'nfs'

Not sure what is causing these errors yet:

    _virtualbox: Warning: Connection reset. Retrying...
    virtualbox: Warning: Remote connection disconnect. Retrying..._

**Comment by mikev1963** [comment]
I updated the NFS line to look like this:
    _config.vm.synced_folder '.', '/vagrant',
        nfs: true,
        nfs_version: 3,
        nfs_udp: false_

This worked, but still get these errors.  

    _virtualbox: Warning: Connection reset. Retrying...
    virtualbox: Warning: Remote connection disconnect. Retrying..._

But the vm works.

**Comment by geerlingguy** [comment]
Strange; in my testing with the current version of the `geerlingguy/centos7` box, it seems to be working okay with NFS. Is this using the prebuilt box or a customized version you built with Packer?

**Comment by sinisterstumble** [comment]
I have the same issue ...

**Comment by sinisterstumble** [comment]
**dangerous**: try deleting `~/.vagrant.d`. vagrant caches the boxes, so all the subsequent box rebuilds are not actually saved.

**Comment by geerlingguy** [comment]
Going to close this for now. This problem could stem from a number of different problems; it might be best to search through Vagrant issues on GitHub and see other suggestions for fixes. Also please verify whether the problem exists with the latest version of Vagrant and the `geerlingguy/centos7` box.
