### ISSUE TITLE
Update for CentOS 7.4, push new box with VirtualBox 5.2.10 Guest Additions

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-centos-7#32]
See title... basically update all the things!

**Comment by geerlingguy** [comment]
I'm also going to drop VMware support as part of this commit, since I don't have/use it anymore, and don't want to continue supporting it at this time.

**Comment by akulbe** [comment]
What exactly does dropping VMware support mean in this case?

**Comment by akulbe** [comment]
Ah, I looked at the diff. I see it.
