### ISSUE TITLE
Upgrade to Virtualbox Guest Additions 6.0

### ISSUE THREAD

**Issue by pedrofurtado** [geerlingguy/packer-centos-7#35]
@geerlingguy 👍

**Comment by geerlingguy** [comment]
Closing as all development work for my packer boxes is moving into a central repository, see: geerlingguy/packer-boxes#45

**Comment by geerlingguy** [comment]
(Note that I have been regularly updating this project and the Vagrant box is on Guest Additions 6.0.14 and updated every month or so.)
