### ISSUE TITLE
Push an updated box to https://atlas.hashicorp.com/geerlingguy/boxes/centos7 ??

### ISSUE THREAD

**Issue by jeffwidman** [geerlingguy/packer-centos-7#6]
Appreciate you making this available. I use your pre-built box here: https://atlas.hashicorp.com/geerlingguy/boxes/centos7

Unfortunately, when I `vagrant up`, the plugin https://github.com/dotless-de/vagrant-vbguest fails (more accurately, it correctly jumpstarts the guest additions build, but the build itself fails). When I SSH in and run `yum update`, and then reboot the box, the guest additions install works correctly. So something in the base box is outdated and causing the guest additions build to fail. 

It looks like there's a few commits to this github repo that updated the CentOS build and EPEL version, but they haven't been pushed to the the pre-built base box...  I have a hunch they might fix this issue that I'm hitting. 

Mind pushing a new version up to Atlas?

**Comment by geerlingguy** [comment]
Working on it today :)

**Comment by geerlingguy** [comment]
Closing out this issue; it's almost finished uploading, and I'll be pushing out the update in just a minute!

**Comment by jeffwidman** [comment]
Thanks!

Looks like it still needs to be marked as "released" on Atlas though? 
https://atlas.hashicorp.com/geerlingguy/boxes/centos7

Here's the relevant docs: https://vagrantcloud.com/docs/versions

**Comment by geerlingguy** [comment]
@jeffwidman - Right you are! I got distracted, never hit the button to publish the revision. It's up now.

**Comment by jeffwidman** [comment]
Thanks! Huge time saver to have a pre-built box.
